apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/prj-poc-001/locations/asia-south1-a/clusters/cicd-cluster

